export const HOME_RAIL_ITEM_LIMIT = 14;
export const HOME_RAIL_LIBRARY_ITEM_COUNT = 1;
export const HOME_RAIL_TOTAL_ITEM_LIMIT = HOME_RAIL_ITEM_LIMIT + HOME_RAIL_LIBRARY_ITEM_COUNT;
export const HOME_RAIL_LIBRARY_TITLE = 'Library';
export const HOME_RAIL_CARD_SIZE_REM = 12.75;
export const HOME_LIBRARY_GRID_COLUMN_COUNT = 5;
export const HOME_LIBRARY_GRID_VISIBLE_ROW_COUNT = 3;
